package com.mozart.model.ejb.facade;

import java.util.List;

import javax.ejb.Remote;

import com.mozart.model.ejb.entity.HotelEJB;
import com.mozart.model.ejb.entity.MovimentoEstoqueEJB;
import com.mozart.model.exception.MozartSessionException;
import com.mozart.model.vo.ItemEstoqueVO;
import com.mozart.model.vo.MovimentoEstoqueVO;

@Remote
public interface EstoqueSession {

	public static final String QUERY_PESQUISAR_MOVIMENTO_ESTOQUE = " SELECT "
			+ "\n\t" + " IR.NOME_ITEM,"
			+ "\n\t" + " ME.TIPO_MOVIMENTO,"
			+ "\n\t" + " NU.UNIDADE,"
			+ "\n\t" + " ME.QUANTIDADE,"
			+ "\n\t" + " ME.VALOR_UNITARIO,"
			+ "\n\t" + " ME.VALOR_TOTAL,"
			+ "\n\t" + " CCC.DESCRICAO_CENTRO_CUSTO,"
			+ "\n\t" + " FR.NOME_FANTASIA,"
			+ "\n\t" + " ME.NUM_DOCUMENTO,"
			+ "\n\t" + " ME.DATA_MOVIMENTO,"
			+ "\n\t" + " TI.NOME_TIPO,"
			+ "\n\t" + " HM.SIGLA HOTEL_MUTUO,"
			+ "\n\t" + " ME.ID_MOVIMENTO_ESTOQUE_PORCAO,"
			+ "\n\t" + " H.SIGLA HOTEL,"
			+ "\n\t" + " ME.ID_MOVIMENTO_ESTOQUE"
			+ "\n\t" + " FROM MOVIMENTO_ESTOQUE ME"
			+ "\n\t" + " JOIN HOTEL H "
			+ "\n\t" + " ON ME.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + " LEFT JOIN FORNECEDOR_REDE FR"
			+ "\n\t" + " 	ON H.ID_REDE_HOTEL = FR.ID_REDE_HOTEL AND ME.ID_FORNECEDOR = FR.ID_FORNECEDOR"
			+ "\n\t" + " LEFT JOIN CENTRO_CUSTO_CONTABIL CCC"
			+ "\n\t" + " 	ON ME.ID_CENTRO_CUSTO = CCC.ID_CENTRO_CUSTO_CONTABIL AND H.ID_REDE_HOTEL = CCC.ID_REDE_HOTEL"
			+ "\n\t" + " JOIN ITEM_REDE IR"
			+ "\n\t" + " 	ON H.ID_REDE_HOTEL = IR.ID_REDE_HOTEL AND ME.ID_ITEM = IR.ID_ITEM"
			+ "\n\t" + " LEFT JOIN NFE_UNIDADE NU "
			+ "\n\t" + " 	ON IR.ID_UNIDADE_ESTOQUE = NU.ID_NFE_UNIDADE "
			+ "\n\t" + " JOIN TIPO_ITEM TI "
			+ "\n\t" + " 	ON IR.ID_TIPO_ITEM = TI.ID_TIPO_ITEM "
			+ "\n\t" + " LEFT JOIN HOTEL HM"
			+ "\n\t" + " 	ON ME.ID_HOTEL_MUTUO = HM.ID_HOTEL";
	
	public static final String QUERY_PESQUISAR_VALOR_UNITARIO_ITEM = " SELECT "
			+ "\n\t" + " ITEM_ESTOQUE.ID_ITEM," 
		    + "\n\t" + " ITEM_ESTOQUE.ID_REDE_HOTEL, "
		    + "\n\t" + " TRUNC ( "
		    + "\n\t" + " NVL ( "
		    + "\n\t" + " (  NVL (Y.VT, 0) "
		    + "\n\t" + " - NVL (X.VT, 0) "
		    + "\n\t" + " - NVL (Z.VT, 0) "
		    + "\n\t" + " + NVL (W.VT, 0) "
		    + "\n\t" + " + NVL (S.VT, 0)), "
		    + "\n\t" + " 1) "
		    + "\n\t" + " / DECODE ( "
		    + "\n\t" + " (  NVL (Y.Q, 0) "
		    + "\n\t" + " - NVL (X.Q, 0) "
		    + "\n\t" + " - NVL (Z.Q, 0) "
		    + "\n\t" + " + NVL (W.Q, 0) "
		    + "\n\t" + " + NVL (S.Q, 0)), "
		    + "\n\t" + " 0, 1, "
		    + "\n\t" + " (  NVL (Y.Q, 0) "
		    + "\n\t" + " - NVL (X.Q, 0) "
		    + "\n\t" + " - NVL (Z.Q, 0) "
		    + "\n\t" + " + NVL (W.Q, 0) "
		    + "\n\t" + " + NVL (S.Q, 0))), "
		    + "\n\t" + " 2) "
		    + "\n\t" + " VLM, "
		    + "\n\t" + " (  NVL (Y.Q, 0) "
		    + "\n\t" + " - NVL (X.Q, 0) "
		    + "\n\t" + " - NVL (Z.Q, 0) "
		    + "\n\t" + " + NVL (W.Q, 0) "
		    + "\n\t" + " + NVL (S.Q, 0)) "
		    + "\n\t" + " QUANT "
		    + "\n\t" + " FROM item_rede ITEM_ESTOQUE, "
		    + "\n\t" + " HOTEL, "
		    + "\n\t" + " (  SELECT M.ID_ITEM, SUM (M.QUANTIDADE) Q, SUM (M.VALOR_TOTAL) VT "
	        + "\n\t" + " FROM MOVIMENTO_ESTOQUE M "
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (M.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE M.TIPO_MOVIMENTO IN ('S') "
	        + "\n\t" + " AND TRUNC (M.DATA_MOVIMENTO) BETWEEN TRUNC (CD.ESTOQUE, 'MM') AND TRUNC (CD.ESTOQUE) "
	        + "\n\t" + " AND M.ID_HOTEL = ?1 "
	        + "\n\t" + " GROUP BY M.ID_ITEM) X, "
	        + "\n\t" + " (  SELECT M.ID_ITEM, "
	        + "\n\t" + " SUM (M.QUANTIDADE) Q, "
	        + "\n\t" + " SUM (M.VALOR_TOTAL) VT "
	        + "\n\t" + " FROM MOVIMENTO_ESTOQUE M "
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (M.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE M.TIPO_MOVIMENTO IN ('E', 'D') "
	        + "\n\t" + " AND TRUNC (M.DATA_MOVIMENTO) BETWEEN TRUNC (CD.ESTOQUE, 'MM') AND TRUNC (CD.ESTOQUE) "
	        + "\n\t" + " AND M.ID_HOTEL = ?2 "
	        + "\n\t" + " GROUP BY ID_ITEM) Y, "
	        + "\n\t" + " (  SELECT M.ID_ITEM, "
	        + "\n\t" + " M.DATA_MOVIMENTO, "
	        + "\n\t" + " M.VALOR_UNITARIO, "
	        + "\n\t" + " MAX (M.ID_MOVIMENTO_ESTOQUE) "
	        + "\n\t" + " FROM MOVIMENTO_ESTOQUE M "
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (M.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE TIPO_MOVIMENTO IN ('E') "
	        + "\n\t" + " AND TRUNC (M.DATA_MOVIMENTO) BETWEEN TRUNC (CD.ESTOQUE, 'MM') AND TRUNC (CD.ESTOQUE) "
	        + "\n\t" + " AND M.ID_HOTEL = ?3 "
	        + "\n\t" + " GROUP BY M.ID_ITEM, M.DATA_MOVIMENTO, M.VALOR_UNITARIO) P, "
	        + "\n\t" + " (  SELECT M.ID_ITEM, "
	        + "\n\t" + " SUM (M.QUANTIDADE) Q, "
	        + "\n\t" + " SUM (M.VALOR_TOTAL) VT "
	        + "\n\t" + " FROM MOVIMENTO_ESTOQUE M "
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (M.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE M.TIPO_MOVIMENTO IN ('P') "
	        + "\n\t" + " AND M.ID_MOVIMENTO_ESTOQUE_PORCAO IS NULL "
	        + "\n\t" + " AND TRUNC (M.DATA_MOVIMENTO) BETWEEN TRUNC (CD.ESTOQUE, 'MM') AND TRUNC (CD.ESTOQUE) "
	        + "\n\t" + " AND M.ID_HOTEL = ?4 "
	        + "\n\t" + " GROUP BY M.ID_ITEM) Z, "
	        + "\n\t" + " (  SELECT M.ID_ITEM, "
	        + "\n\t" + " SUM (M.QUANTIDADE) Q, "
	        + "\n\t" + " SUM (M.VALOR_TOTAL) VT "
	        + "\n\t" + " FROM MOVIMENTO_ESTOQUE M "
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (M.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE M.TIPO_MOVIMENTO IN ('P') "
	        + "\n\t" + " AND M.ID_MOVIMENTO_ESTOQUE_PORCAO IS NOT NULL "
	        + "\n\t" + " AND TRUNC (M.DATA_MOVIMENTO) BETWEEN TRUNC (CD.ESTOQUE, 'MM') AND TRUNC (CD.ESTOQUE) "
	        + "\n\t" + " AND M.ID_HOTEL = ?5 "
	        + "\n\t" + " GROUP BY M.ID_ITEM) W, "
	        + "\n\t" + " (  SELECT S.ID_ITEM, "
	        + "\n\t" + " SUM (S.QUANT_ESTOQUE) Q, "
	        + "\n\t" + " SUM (S.QUANT_ESTOQUE) * SUM (S.VALOR_MEDIO) VT "
	        + "\n\t" + " FROM SALDOS_ESTOQUE_MENSAL S " 
	        + "\n\t" + " JOIN " 
	        + "\n\t" + " CONTROLA_DATA CD " 
	        + "\n\t" + " ON (S.ID_HOTEL = CD.ID_HOTEL) " 
	        + "\n\t" + " WHERE ANO = "
	        + "\n\t" + " DECODE (TO_CHAR (CD.ESTOQUE, 'MM') - 1, " 
	        + "\n\t" + " 0, TO_CHAR (CD.ESTOQUE, 'YYYY') - 1, " 
	        + "\n\t" + " TO_CHAR (CD.ESTOQUE, 'YYYY')) "
	        + "\n\t" + " AND MES = "
	        + "\n\t" + " DECODE (TO_CHAR (CD.ESTOQUE, 'MM') - 1, " 
	        + "\n\t" + " 0, 12, "
	        + "\n\t" + " TO_CHAR (CD.ESTOQUE, 'MM') - 1) "
	        + "\n\t" + " AND S.ID_HOTEL = ?6 "
	        + "\n\t" + " GROUP BY ID_ITEM) S "
	        + "\n\t" + " WHERE     X.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND Y.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND Z.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND W.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND S.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND P.ID_ITEM(+) = ITEM_ESTOQUE.ID_ITEM "
	        + "\n\t" + " AND ITEM_ESTOQUE.ID_REDE_HOTEL = HOTEL.ID_REDE_HOTEL "
	        + "\n\t" + " AND HOTEL.ID_HOTEL = ?7 "
	        + "\n\t" + " AND ITEM_ESTOQUE.ID_ITEM = ?8 "
	        + "\n\t" + " ORDER BY ITEM_ESTOQUE.ID_ITEM";
	
	public static final String QUERY_PESQUISAR_VALOR_UNITARIO_DEVOLUCAO_ITEM = " SELECT "
			+ "\n\t" + " VALOR_UNITARIO, MAX(ID_MOVIMENTO_ESTOQUE), QUANTIDADE FROM MOVIMENTO_ESTOQUE  "
		    + "\n\t" + " WHERE ID_ITEM = ?1 " 
		    + "\n\t" + " AND ID_HOTEL = ?2 " 
		    + "\n\t" + " AND ID_CENTRO_CUSTO = ?3 " 
		    + "\n\t" + " AND TIPO_MOVIMENTO = 'S' " 
		    + "\n\t" + " GROUP BY VALOR_UNITARIO, QUANTIDADE ";
			
	public static final String QUERY_MOVIMENTO_ESTOQUE_INSERIR_FECHAMENTO = " SELECT "
			+ "\n\t" + " SEQ_MOVIMENTO_ESTOQUE.NEXTVAL ID_MOVIMENTO_CONTABIL,   "
		    + "\n\t" + " FTP.ID_ITEM, MR.ID_HOTEL,PV.ID_CENTRO_CUSTO_CONTABIL ID_CENTRO_CUSTO,PV.DATA_PV DATA_MOVIMENTO, 'B' TIPO_MOVIMENTO, " 
		    + "\n\t" + " PV.DATA_PV DATA_DOCUMENTO, MR.NUM_NOTA NUM_DOCUMENTO, FTP.QUANTIDADE,H.ID_REDE_HOTEL " 
		    + "\n\t" + " FROM MOVIMENTO_RESTAURANTE MR " 
		    + "\n\t" + " JOIN PRATO PR ON (MR.ID_PRATO = PR.ID_PRATO)  " 
		    + "\n\t" + " JOIN FICHA_TECNICA_PRATO FTP ON (PR.ID_PRATO = FTP.ID_PRATO) "
		    + "\n\t" + " JOIN ITEM_ESTOQUE IE ON (FTP.ID_ITEM = IE.ID_ITEM) "
		    + "\n\t" + " JOIN PONTO_VENDA PV ON (MR.ID_PONTO_VENDA = PV.ID_PONTO_VENDA) "
		    + "\n\t" + " JOIN HOTEL H ON (MR.ID_HOTEL = H.ID_HOTEL) "
		    + "\n\t" + " WHERE PR.ID_HOTEL = ?1 "
		    + "\n\t" + " AND MR.ID_PONTO_VENDA = ?2 "
		    + "\n\t" + " AND MR.NUM_NOTA = ?3 "
		    + "\n\t" + " AND IE.CONTROLADO = 'S' ";		
	
	public static final String QUERY_PESQUISAR_VALOR_UNITARIO_TRANSFERENCIA_CUSTO = " SELECT "
			+ "\n\t" + " ME.VALOR_UNITARIO, ME.ID_MOVIMENTO_ESTOQUE, 0 AS QUANTIDADE FROM MOVIMENTO_ESTOQUE ME, "
			+ "\n\t" + " CONTROLA_DATA CD, "
		    + "\n\t" + " (SELECT MAX (ID_MOVIMENTO_ESTOQUE) ID_MOVIMENTO_ESTOQUE " 
		    + "\n\t" + " FROM MOVIMENTO_ESTOQUE ME " 
		    + "\n\t" + " WHERE     ME.TIPO_MOVIMENTO IN ('S') " 
		    + "\n\t" + " AND ME.ID_ITEM = ?1 "
		    + "\n\t" + " AND ME.ID_CENTRO_CUSTO = ?2) E " 
		    + "\n\t" + " WHERE     ME.ID_ITEM = ?3 "
		    + "\n\t" + " AND ME.ID_CENTRO_CUSTO = ?4 " 
		    + "\n\t" + " AND ME.TIPO_MOVIMENTO = 'S' " 
		    + "\n\t" + " AND ME.DATA_MOVIMENTO <= CD.ESTOQUE " 
		    + "\n\t" + " AND E.ID_MOVIMENTO_ESTOQUE = ME.ID_MOVIMENTO_ESTOQUE "
		    + "\n\t" + " AND ME.ID_HOTEL = ?5 " 
		    + "\n\t" + " GROUP BY ME.ID_MOVIMENTO_ESTOQUE, ME.VALOR_UNITARIO ";
	
	public static final String QUERY_PESQUISAR_QUANTIDADE_TRANSFERENCIA_CUSTO = "  SELECT DISTINCT "
			+ "\n\t" + "       ME.ID_CENTRO_CUSTO, "
			+ "\n\t" + "       ME.ID_ITEM, "
			+ "\n\t" + "       ((NVL (SA.SA, 0) "
			+ "\n\t" + "        - NVL (A.A, 0) "
			+ "\n\t" + "        - NVL (B.B, 0) "
			+ "\n\t" + "        - NVL (D.D, 0) "
			+ "\n\t" + "        - NVL (C.C, 0) "
			+ "\n\t" + "        - NVL (T.T, 0) "
			+ "\n\t" + "        + NVL (S.S, 0) "
			+ "\n\t" + "        + NVL (R.R, 0))) "
			+ "\n\t" + "          QTDE "
			+ "\n\t" + "  FROM MOVIMENTO_ESTOQUE ME, "
			+ "\n\t" + "       CONTROLA_DATA CD, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) A "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('A') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) A, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) B "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('B') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) B, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) C "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('C') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) C, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) D "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('D') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) D, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) S "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('S') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) S, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) T "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('T') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) T, "
			+ "\n\t" + "       (  SELECT M.ID_CENTRO_CUSTO, M.ID_ITEM, SUM (M.QUANTIDADE) R "
			+ "\n\t" + "            FROM MOVIMENTO_ESTOQUE M "
			+ "\n\t" + "                 JOIN HOTEL H "
			+ "\n\t" + "                    ON (H.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "                 JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                    ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                        AND I.ID_ITEM = M.ID_ITEM "
			+ "\n\t" + "                        AND I.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                    ON (    H.ID_REDE_HOTEL = C.ID_REDE_HOTEL "
			+ "\n\t" + "                        AND M.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                        AND C.CONTROLADO = 'S') "
			+ "\n\t" + "                 JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                    ON (CD.ID_HOTEL = M.ID_HOTEL) "
			+ "\n\t" + "           WHERE M.ID_HOTEL = ?1 "
			+ "\n\t" + "                 AND TO_CHAR (M.DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "                        TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "                 AND M.TIPO_MOVIMENTO IN ('R') "
			+ "\n\t" + "        GROUP BY M.ID_CENTRO_CUSTO, M.ID_ITEM) R, "
			+ "\n\t" + "       (SELECT SEP.ID_ITEM, "
			+ "\n\t" + "               C.ID_CENTRO_CUSTO_CONTABIL, "
			+ "\n\t" + "               (SEP.QUANT_ESTOQUE) SA "
			+ "\n\t" + "          FROM SALDOS_ESTOQUE_PDV SEP "
			+ "\n\t" + "               JOIN HOTEL H "
			+ "\n\t" + "                  ON (H.ID_HOTEL = SEP.ID_HOTEL) "
			+ "\n\t" + "               JOIN ITEM_ESTOQUE I "
			+ "\n\t" + "                  ON (    I.ID_HOTEL = H.ID_HOTEL "
			+ "\n\t" + "                      AND SEP.ID_ITEM = I.ID_ITEM "
			+ "\n\t" + "                      AND I.CONTROLADO = 'S') "
			+ "\n\t" + "               JOIN CENTRO_CUSTO_CONTABIL C "
			+ "\n\t" + "                  ON (    SEP.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO_CONTABIL "
			+ "\n\t" + "                      AND C.ID_REDE_HOTEL = H.ID_REDE_HOTEL "
			+ "\n\t" + "                      AND C.CONTROLADO = 'S') "
			+ "\n\t" + "               JOIN CONTROLA_DATA CD "
			+ "\n\t" + "                  ON (CD.ID_HOTEL = H.ID_HOTEL) "
			+ "\n\t" + "         WHERE SEP.ID_HOTEL = ?1 "
			+ "\n\t" + "               AND ANO = "
			+ "\n\t" + "                      DECODE (TO_CHAR (CD.ESTOQUE, 'MM'), "
			+ "\n\t" + "                              1, TO_CHAR (CD.ESTOQUE, 'YYYY') - 1, "
			+ "\n\t" + "                              TO_CHAR (CD.ESTOQUE, 'YYYY')) "
			+ "\n\t" + "               AND MES = "
			+ "\n\t" + "                      DECODE (TO_CHAR (CD.ESTOQUE, 'MM'), "
			+ "\n\t" + "                              1, 12, "
			+ "\n\t" + "                              TO_CHAR (CD.ESTOQUE, 'MM') - 1)) SA "
			+ "\n\t" + " WHERE ME.ID_HOTEL = ?1 AND ME.ID_HOTEL = CD.ID_HOTEL "
			+ "\n\t" + "       AND TO_CHAR (DATA_MOVIMENTO, 'MM/YYYY') = "
			+ "\n\t" + "              TO_CHAR (CD.ESTOQUE, 'MM/YYYY') "
			+ "\n\t" + "       AND ME.ID_ITEM = A.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = B.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = C.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = D.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = S.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = T.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = R.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = SA.ID_ITEM(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = A.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = B.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = C.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = D.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = S.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = T.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = R.ID_CENTRO_CUSTO(+) "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = SA.ID_CENTRO_CUSTO_CONTABIL(+) "
			+ "\n\t" + "       AND ME.ID_ITEM = ?2 "
			+ "\n\t" + "       AND ME.ID_CENTRO_CUSTO = ?3 "
			+ "\n\t" + "       AND (   A.A <> 0 "
			+ "\n\t" + "            OR B.B <> 0 "
			+ "\n\t" + "            OR C.C <> 0 "
			+ "\n\t" + "            OR D.D <> 0 "
			+ "\n\t" + "            OR S.S <> 0 "
			+ "\n\t" + "            OR T.T <> 0 "
			+ "\n\t" + "            OR R.R <> 0)";
	
	public abstract Object persist(Object paramObject)
			throws MozartSessionException;
	
	public abstract Object alterar(Object paramObject)
			throws MozartSessionException;
	
	public abstract Object obter(Class paramClass, Object paramObject)
			throws MozartSessionException;
	
	public abstract Object refresh(Class paramClass, Object paramObject)
			throws MozartSessionException;

	public abstract void excluir(Object paramObject)
			throws MozartSessionException;

	public abstract List<MovimentoEstoqueVO> pesquisarMovimentoEstoque(MovimentoEstoqueVO movimentoEstoqueVO)
			throws MozartSessionException;
	
	public abstract void salvarMovimentoEstoque(MovimentoEstoqueEJB movimentoEstoque) throws MozartSessionException;
	
	public abstract void salvarMovimentoEstoqueReduzido(MovimentoEstoqueEJB movimentoEstoque) throws MozartSessionException;

	public abstract void encerrar(HotelEJB pHotelEJB) throws MozartSessionException;
	
	public abstract Long obterNextVal() throws MozartSessionException;
	
	public abstract List<ItemEstoqueVO> pesquisarValorUnitarioItem(ItemEstoqueVO itemEstoque) throws MozartSessionException;
	
	public abstract List<ItemEstoqueVO> pesquisarValorUnitarioDevolucaoItem(ItemEstoqueVO itemEstoque) throws MozartSessionException;
	
	public abstract void salvarSaidaMovimentoEstoque(MovimentoEstoqueEJB movimentoEstoque) throws MozartSessionException;
	
	public MovimentoEstoqueVO pesquisarMovimentoEstoqueFechamento(MovimentoEstoqueVO movimentoEstoqueVO) throws MozartSessionException;
	
	public void salvarFechamentoMovimentoEstoque(MovimentoEstoqueVO movimentoEstoque) throws MozartSessionException;
	
	public List<ItemEstoqueVO> pesquisarValorUnitarioTransferenciaCusto(ItemEstoqueVO itemEstoque) throws MozartSessionException; 
	
	public List<ItemEstoqueVO> pesquisarQuantidadeTransferenciaCusto(ItemEstoqueVO itemEstoque) throws MozartSessionException;
}