package com.mozart.model.ejb.facade;

import java.util.List;

import javax.ejb.Remote;

import com.mozart.model.exception.MozartSessionException;
import com.mozart.model.vo.MarketingPorEmpresaVO;

@Remote
public interface MarketingSession {

	
	//SQL += " AND INSTR(?1, ';'||MOV.ID_HOTEL||';') > 0\n";
	String QRY_POR_EMPRESA = 
		" SELECT * FROM ( "+
		" SELECT HOP.EMAIL, H.SIGLA, E.ID_EMPRESA, CRS.ID_CENTRAL_RESERVAS, R.ID_RESERVA, CHK.ID_CHECKIN, R.FORMA_RESERVA, ER.NOME_FANTASIA,TE.TIPO_EMPRESA, C.CIDADE, C.ESTADO, C.PAIS, P.PROMOTOR, CRS.NOME_FANTASIA CRS, "+  
		" HOP.NOME_HOSPEDE || ' '|| HOP.SOBRENOME_HOSPEDE||' - '||HOP.ID_HOSPEDE NOME_HOSPEDE, GE.NOME_GRUPO, "+ 
		" CHK.DATA_ENTRADA DATA_ENTRADA, CHK.DATA_SAIDA DATA_SAIDA, "+ 
		" NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0) RN, NVL(VALOR_DIARIA.VALOR,0) VALOR_DIARIA, NVL(VALOR_EXTRA.VALOR,0) VALOR_EXTRA, "+
		" NVL(VALOR_DIARIA.VALOR,0) + NVL(VALOR_EXTRA.VALOR,0) VALOR_TOTAL, "+
		" NVL(VALOR_DIARIA.VALOR,0)/DECODE(NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0),0,1,NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0)) DIARIA_MEDIA, "+
		" NVL(VALOR_EXTRA.VALOR,0)/DECODE(NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0),0,1,NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0)) DIARIA_MEDIA_EXTRA, "+ 
		" NVL(VALOR_DIARIA.VALOR,0) + NVL(VALOR_EXTRA.VALOR,0)/DECODE(NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0),0,1,NVL(RN_POSITIVO.QTDE,0) - NVL(RN_NEGATIVO.QTDE,0))TICKET_MEDIO, LOG.NICK, ORIGEM.CIDADE||'-'||ORIGEM.UF CIDADE_ORIGEM, DESTINO.CIDADE||'-'||DESTINO.UF CIDADE_DESTINO "+   
		" FROM CHECKIN CHK, EMPRESA E, EMPRESA_REDE ER, EMPRESA_HOTEL EH, CONTROLA_DATA CD, PROMOTOR P, TIPO_EMPRESA TE, V_CIDADE ORIGEM, V_CIDADE DESTINO, V_CIDADE C, RESERVA R, CENTRAL_RESERVAS CRS, HOTEL H, "+
		" ROOM_LIST RL, HOSPEDE HOP, GRUPO_ECONOMICO GE, "+
		
		" (SELECT MOV.ID_ROOM_LIST, COUNT(*) QTDE "+ 
		" FROM MOVIMENTO_APARTAMENTO MOV, TIPO_LANCAMENTO TL "+
		" WHERE INSTR(?1, ';'||MOV.ID_HOTEL||';') > 0 "+
		" AND MOV.ID_TIPO_LANCAMENTO = TL.ID_TIPO_LANCAMENTO "+
		" AND TL.ID_IDENTIFICA_LANCAMENTO IN (2, 26) "+
		" AND TRUNC(MOV.DATA_LANCAMENTO) BETWEEN TRUNC(?2) AND TRUNC(?3) "+
		" GROUP BY MOV.ID_ROOM_LIST) RN_POSITIVO, "+
		
		" (SELECT ID_ROOM_LIST, COUNT(*) QTDE "+ 
		" FROM MOVIMENTO_APARTAMENTO MOV, TIPO_LANCAMENTO TL "+
		" WHERE INSTR(?4, ';'||MOV.ID_HOTEL||';') > 0 "+
		" AND MOV.ID_TIPO_LANCAMENTO = TL.ID_TIPO_LANCAMENTO "+
		" AND TL.ID_IDENTIFICA_LANCAMENTO IN (3) "+
		" AND TRUNC(MOV.DATA_LANCAMENTO) BETWEEN TRUNC(?5) AND TRUNC(?6) "+
		" GROUP BY MOV.ID_ROOM_LIST) RN_NEGATIVO, "+	 
		
		" (SELECT MOV.ID_ROOM_LIST, SUM(VALOR_LANCAMENTO) VALOR  "+
		" FROM MOVIMENTO_APARTAMENTO MOV, TIPO_LANCAMENTO TL "+
		" WHERE INSTR(?7, ';'||MOV.ID_HOTEL||';') > 0 "+
		" AND MOV.ID_TIPO_LANCAMENTO = TL.ID_TIPO_LANCAMENTO "+
		" AND TL.ID_IDENTIFICA_LANCAMENTO IN (3,28,2,26) "+
		" AND TRUNC(MOV.DATA_LANCAMENTO) BETWEEN TRUNC(?8) AND TRUNC(?9) "+
		" GROUP BY MOV.ID_ROOM_LIST) VALOR_DIARIA, "+
		
		" (SELECT MOV.ID_ROOM_LIST, SUM(VALOR_LANCAMENTO) VALOR "+ 
		" FROM MOVIMENTO_APARTAMENTO MOV, TIPO_LANCAMENTO TL, IDENTIFICA_LANCAMENTO IL "+
		" WHERE INSTR(?10, ';'||MOV.ID_HOTEL||';') > 0 "+
		" AND MOV.ID_TIPO_LANCAMENTO = TL.ID_TIPO_LANCAMENTO "+
		" AND TL.ID_IDENTIFICA_LANCAMENTO = IL.ID_IDENTIFICA_LANCAMENTO "+
		" AND RECEITA_CHECKOUT = '1' "+
		" AND TL.ID_IDENTIFICA_LANCAMENTO NOT IN (3,28,2,26) "+
		" AND TRUNC(MOV.DATA_LANCAMENTO) BETWEEN TRUNC(?11) AND TRUNC(?12) "+
		" GROUP BY MOV.ID_ROOM_LIST) VALOR_EXTRA, "+
		
		" (SELECT LOG.ID_AUDITADO, substr(U.NICK,8,length(U.NICK)) nick "+
		" FROM LOG_USUARIO LOG, USUARIO U  "+
		" WHERE INSTR(?13, ';'||LOG.ID_HOTEL||';') > 0 "+
		" AND LOG.ID_USUARIO = U.ID_USUARIO "+
		" AND LOG.TABELA_AUDITADA = 'RESERVA' "+ 
		" AND LOG.OPERACAO = 'Inclusão' ) LOG"+
		
		" WHERE INSTR(?14, ';'||H.ID_HOTEL||';') > 0 "+ 
		" AND CHK.ID_CHECKIN = RL.ID_CHECKIN "+
		" AND rl.ID_ROOM_LIST = RN_POSITIVO.ID_ROOM_LIST(+) "+
		" AND rl.ID_ROOM_LIST = RN_NEGATIVO.ID_ROOM_LIST(+) "+
		" AND rl.ID_ROOM_LIST = VALOR_DIARIA.ID_ROOM_LIST(+) "+
		" AND rl.ID_ROOM_LIST = VALOR_EXTRA.ID_ROOM_LIST(+) "+
		" AND RL.ID_HOSPEDE = HOP.ID_HOSPEDE "+
		" AND CHK.ID_RESERVA = R.ID_RESERVA(+) "+
		" AND H.ID_HOTEL = CD.ID_HOTEL "+ 
		" AND CHK.ID_EMPRESA = EH.ID_EMPRESA "+
		" AND CHK.ID_HOTEL = EH.ID_HOTEL "+ 
		" AND CHK.ID_CIDADE_PROCEDENCIA = ORIGEM.ID_CIDADE "+
		" AND CHK.ID_CIDADE_DESTINO = DESTINO.ID_CIDADE "+
		" AND CD.ID_REDE_HOTEL = ER.ID_REDE_HOTEL "+
		" AND E.ID_EMPRESA = ER.ID_EMPRESA "+
		" AND ER.ID_EMPRESA = EH.ID_EMPRESA "+
		" AND ER.ID_GRUPO_ECONOMICO = GE.ID_GRUPO_ECONOMICO(+) "+
		" AND CD.ID_HOTEL = EH.ID_HOTEL "+
		" AND ER.ID_PROMOTOR = P.ID_PROMOTOR "+
		" AND TE.ID_TIPO_EMPRESA = EH.ID_TIPO_EMPRESA "+
		" AND TE.ID_REDE_HOTEL = CD.ID_REDE_HOTEL "+
		" AND E.ID_CIDADE = C.ID_CIDADE "+
		" AND R.ID_CENTRAL_RESERVAS = CRS.ID_CENTRAL_RESERVAS(+) "+
		" AND R.ID_RESERVA = LOG.ID_AUDITADO(+) "+
		" AND (TRUNC(CHK.DATA_ENTRADA) BETWEEN TRUNC(?15) AND TRUNC(?16) OR TRUNC(CHK.DATA_saida) BETWEEN TRUNC(?17) AND TRUNC(?18)) "+  
		" ORDER BY R.ID_RESERVA) "+
		" WHERE VALOR_TOTAL <> 0 ";
		
	List<MarketingPorEmpresaVO> pesquisarReservasPorEmpreasa(MarketingPorEmpresaVO pFiltro) throws MozartSessionException;

	void executarRDSAnual(Long idHotel, String ateDia, String ateMes,
			String anoInicial, String anoFinal) throws MozartSessionException;
	
}
